version: '3'
services:
  bigstream:
    image: "igridproject/bigstream"
    container_name: bs${PREFIX_NO}_bigstream
    restart: always
    networks:
     - bsnet
    ports:
     - "${PREFIX_NO}980:19980"
     - "${PREFIX_NO}080:19080"
     - "${PREFIX_NO}180:19180"
    volumes:
     - ${VOLUME}/bigstream/data:/var/bigstream/data
  redis:
    image: "redis:${REDIS_TAG}"
    command: redis-server --appendonly yes
    container_name: bs${PREFIX_NO}_redis_server
    restart: always
    networks:
       bsnet:
	      aliases:
		     - redis-server
    ports:
     - "6379:6379"
    volumes:
     - ${VOLUME}/redis/data:/data
  rabbitmq:
    image: "igridproject/rabbitmq"
    command: rabbitmq-server --hostname rabbitmq-server
    container_name: bs${PREFIX_NO}_rabbitmq_server
    restart: always
    networks:
       bsnet:
	      aliases:
		     - rabbitmq-server
    ports:
     - "5672:5672"
networks:
  bsnet:
     driver: bridge